### ISSUE TITLE
ParticipantObjectIdentificationType does not support ParticipantObjectDescription with extension for DICOMObjectDescriptionContents

### ISSUE THREAD

**Issue by earlraneses** [oehf/ipf-oht-atna#12]
Any plans on supporting this element?

![participantobjectdescription](https://user-images.githubusercontent.com/33829405/40103206-a12f55ec-5927-11e8-93b9-7e35920414d2.JPG)

reference:
[A.5 Audit Trail Message Format Profile](http://dicom.nema.org/dicom/2013/output/chtml/part15/sect_A.5.html)

**Comment by ohr** [comment]
This project is deprecated as of IPF 3.5.0
The ipf-commons-audit module of IPF 3.5.0 provides a reimplementation of ATNA auditing, also supporting the element you mentioned.
