### ISSUE TITLE
ATNA TLS configuration has side effects on other interfaces in the same JVM

### ISSUE THREAD

**Issue by Thopap** [oehf/ipf-oht-atna#2]
I have configured ATNA as described in http://oehf.github.io/ipf/ipf-platform-camel-ihe/atna.html
especially using https.ciphersuites and https.protocols.

We have identified that ATNA TLS set this configuration as JVM system properties during startup, which has side effect on other interfaces as well. E.g. setting https.protocols = TLSv1 in the atna configuration will also reduce the supported TLS version on the HTTPs interface of the application server (TLSv1.2 will be rejected).

The underlying issue seems to be present in `org.openhealthtools.ihe.atna.nodeauth.SecurityDomain.setOrClearSystemProperties(String, Properties)` where the ATNA component call System.setProperty.

As a potential workaround, we programmatically set the current JVM defaults into this configuration, so it does not change the default behavior:
`
SSLParameters defaultSSLParameters = SSLContext.getDefault().getDefaultSSLParameters();
this.securityProperties.setProperty("https.ciphersuites",
          toCommaSeparatedString(defaultSSLParameters.getCipherSuites()));
this.securityProperties.setProperty("https.protocols",
           toCommaSeparatedString(defaultSSLParameters.getProtocols()));
`

**Comment by ohr** [comment]
see comments in #3

**Comment by ohr** [comment]
I also think that `SecurityDomain` should not pamper the system-wide environment, but the security environment should be the driver to configure the default SecurityDomain. 

Also, Camel has its own utility (http://camel.apache.org/camel-configuration-utilities.html). It is definitely preferrable to have a single source of JSSE setup for all concerns.

We should probably also have an "IHE-compliant" set of JSSE properties for interoperability reasons and to "plug-and-play" in a Connect-a-thon environment; but as these are somewhat outdated, it should not be the default.

Any opinions?

**Comment by ohr** [comment]
I'll introduce yet another system environment variable `org.openhealthtools.ihe.atna.nodeauth.SetDomainEnvironment`. If this is explicitly set to "true", the old behavior is maintained. Otherwise, the SecurityDomain settings are NOT influencing the system properties anymore. 
Obtaining a TLS socket for audit trail will be using the `jdk.tls.client.protocols` system property or `TLSv1.2,TLSv1.1,TLSv1` if it is not set. Mid- to longterm I'd like to get rid of TLS management in this form (also see #3)
