### ISSUE TITLE
ATNA TLS protocol version is restricted to TLSv1.0, configured TLS protocol version is ignored

### ISSUE THREAD

**Issue by Thopap** [oehf/ipf-oht-atna#3]
The ATNA configuration has some properties to configure the TLS protocol (http://oehf.github.io/ipf/ipf-platform-camel-ihe/atna.html), e.g. https.protocols.

In my scenario I have force the ATNA server to only accept TLSv1.2 and configured https.protocols in my ATNA client to also use TLSv1.2.

As a result the TLS handshake was not possible.
If I enable network logging, i always see a "**\* ClientHello, TLSv1" instead of the expected "**\* ClientHello, TLSv1.2".

I expect that the issue is caused by:
`org.openhealthtools.ihe.atna.nodeauth.handlers.TLSEnabledSocketHandler.createSecureSocket(String, int, SecurityDomain, Socket)`

at least the line
`socket.setEnabledProtocols(new String[] {"TLSv1"});`
need to be rewritten to read the value from the securityDomain configuration, e.g.
`socket.setEnabledProtocols(securityDomain.getEnabledProtocols()); //securityDomain need to be extended as well to expose the internal setting`.

**Comment by ohr** [comment]
Yes, the hardcoded TLSv1 is definitely a problem. We should align the configuration of the SecurityDomain to be compliant with the default JSSE environment configuration (cf. https://blogs.oracle.com/java-platform-group/entry/diagnosing_tls_ssl_and_https, http://docs.oracle.com/javase/8/docs/technotes/guides/security/SunProviders.html#SunJSSE_Protocols), taking into account that TLSv1.2 is now the standard.

Using `-Dhttps.protocols` is somewhat questionable, however, as ATNA/TLS is NOT https. 
`-Djdk.tls.client.protocols` looks more applicable to me.

**Comment by ohr** [comment]
Will implement this as proposed. Mid- to long-term we need to get rid of this library and use standard Java mechanisms to define SSL/TLS parameters with which to obtain SSLSockets. 
Currently, IPF only uses this for outgoing TLS connections for Audit Trail. Outgoing secure MLLP, WebService, and FHIR transactions do not use the SecurityDomain for TLS parameters.
