### ISSUE TITLE
AuditSourceIdentificationType does not serialize correctly

### ISSUE THREAD

**Issue by ohr** [oehf/ipf-oht-atna#5]
AuditSourceIdentificationType serializes its AuditSourceTypeCode attributes directly as attribute, but it should render inside a nested AuditSourceTypeCode element. Also, there can be more than one AuditSourceTypeCode.

see schema at http://dicom.nema.org/medical/dicom/current/output/html/part15.html#sect_A.5.1

**Comment by unixoid** [comment]
In http://ihewiki.wustl.edu/wiki/index.php/Syslog_Collector there is a section "What you need to change to convert to DICOM format audit messages" containing the following statement:

> In AuditSourceIdentification elements, remove the AuditSourceTypeCode sub-element, moving its code attribute to the parent AuditSourceIdentification element. If the value of the code attribute is not one of the hard-coded values (single digits 1 through 9) appropriate codeSystemName and originalText attributes will have to be added to the AuditSourceIdentification element.

**Comment by ohr** [comment]
This tool is retired, and the description may not have been updated for quite some time (or may just describe the way this validator has worked). 

The Gazelle EVS Client enforces the DICOM schema (see  e.g. https://gazelle.ihe.net/EVSClient/detailedResult.seam?type=ATNA&oid=1.3.6.1.4.1.12559.11.1.2.1.4.754765), however, there is much confusion on the EU-CAT mailing lists (e.g. https://groups.google.com/forum/#!topic/eu_connectathon/GovNw6pkkio, https://groups.google.com/forum/#!topic/eu_connectathon/TicqhHv0Fao).
Reading the ITI-20 spec, there is no indication that the schema can/should be rearranged as indicated on this page you referred to *except* for the PurposeOfUse stuff.

I won't commit the fix for this until folks come to a common understanding

**Comment by unixoid** [comment]
Ah, ok, thanks for the clarification.  Being a Connectathon participant obviously has its advantages -- for example, one reads the corresponding mailing lists... ;-)

**Comment by ohr** [comment]
Nevertheless, it's a complete mess. DICOM has changed its schema somewhen in 2016. 

CP 1361 Parts 15 Correct ParticipantObjectDescription in DICOM audit message.    Standard        2016b
CP 1362 Parts 15 Correct AuditSourceIdentification in DICOM audit message Standard 2016b

https://groups.google.com/forum/#!topic/eu_connectathon/TicqhHv0Fao gives me the impression that the change is necessary, and one more DICOM CP-1638 is one the way.

Need to check the irregularity with ParticipantObjectDescription.
