### ISSUE TITLE
ATNA messages using TLS is not being send if ATNA repository IP adress instead of hostname is configured

### ISSUE THREAD

**Issue by Thopap** [oehf/ipf-oht-atna#7]
During connectathon testing, an issue was identified with IPF-OHT-ATNA 3.4.1 that ATNA over TLS is throwing the following configuration error if the ATNA server IP instead of the hostname is used:
`org.openhealthtools.ihe.atna.nodeauth.NoSecurityDomainException: No DEFAULT Security Domain available for host ovh3.ihe-europe.net and port 10009
        at org.openhealthtools.ihe.atna.nodeauth.SecurityDomainManager.getSecurityDomain(SecurityDomainManager.java:201) ~[ipf-oht-atna-nodeauth-3.4.1.jar:?]
        at org.openhealthtools.ihe.atna.nodeauth.handlers.AbstractSecureSocketHandler.getSocket(AbstractSecureSocketHandler.java:116) ~[ipf-oht-atna-nodeauth-3.4.1.jar:?]
        at org.openhealthtools.ihe.atna.auditor.sender.TLSSyslogSenderImpl.getTLSSocket(TLSSyslogSenderImpl.java:179) ~[ipf-oht-atna-auditor-3.4.1.jar:?]
        at org.openhealthtools.ihe.atna.auditor.sender.TLSSyslogSenderImpl.sendAuditEvent(TLSSyslogSenderImpl.java:140) ~[ipf-oht-atna-auditor-3.4.1.jar:?]
`

The simple workaround was using 
audit.repository.host=HOSTNAME_OF_RECIPIENT
instead of 
audit.repository.host=IP_OF_RECIPIENT

My first analyse on the issue:
In org.openhealthtools.ihe.atna.nodeauth.SecurityDomainManager.getSecurityDomain(String, int), there is an internal key created based on host and key. The map behind is filled with the initial values from the config file (so IP and Port). But during atna sending event, the method org.openhealthtools.ihe.atna.auditor.sender.TLSSyslogSenderImpl.getTLSSocket(InetAddress, int) perform a hostname resolvement "IP->Hostname" (destination.getHostName()) and the combination hostname + port could not be found in the map where only ip and port is present.

**Comment by Thopap** [comment]
As a workaround (or possible fix) for applications that only use one atna destination. It is possible to create a own implementation of the org.openhealthtools.ihe.atna.auditor.AuditorTLSConfig:

And use "registerDefaultSecurityDomain" instead of "registerURItoSecurityDomain":
```
            SecurityDomain securityDomain = new SecurityDomain(SecurityDomain.DEFAULT_SECURITY_DOMAIN,
                    securityProperties);
            NodeAuthModuleContext nodeContext = NodeAuthModuleContext.getContext();
            SecurityDomainManager securityDomainManager = nodeContext.getSecurityDomainManager();
            securityDomainManager.registerDefaultSecurityDomain(securityDomain);
```

**Comment by ohr** [comment]
won't fix. ATNA has been included in IPF itself
